### PR TITLE
Design Brand Logo and Modify Navbar

### PR DESCRIPTION
**Pull request by iamrishavraj1**
screencapture-file-C-Users-iamri-OneDrive-Desktop-iCoderBootStrap-index-html-2020-10-30-21_25_36
White and Blue Simple Computer Logo (4)

### CODE REVIEW

**Comment by iamrishavraj1** [comment]
@geeks5551 Please Review My PR 👍

**Comment by geeks5551** [comment]
hey @iamrishavraj1 you have to incorporate that logo in the navbar beside the icoder brand name, rest the designing work is fine

**Comment by iamrishavraj1** [comment]
> hey @iamrishavraj1 you have to incorporate that logo in the navbar beside the icoder brand name, rest the designing work is fine

Okay.

**Comment by iamrishavraj1** [comment]
> hey @iamrishavraj1 you have to incorporate that logo in the navbar beside the icoder brand name, rest the designing work is fine

Done the changes and Review my PR @geeks5551

**Comment by iamrishavraj1** [comment]
screencapture-file-C-Users-iamri-OneDrive-Desktop-iCoderBootStrap-index-html-2020-10-31-00_10_03

**Pull request merged**
