### PR TITLE
Add favicon

### PR DESCRIPTION
**Pull request by groomea**
Closes issue #12

### CODE REVIEW

**Comment by geeks5551** [comment]
hey @Racing5372 can you provide live link/screenshots for better reviewing purposes

**Comment by groomea** [comment]
image
Sure, here's an image of the favicon

**Comment by geeks5551** [comment]
@Racing5372 Favicon Looks nice but you have to add it also to the main website's title

**Comment by groomea** [comment]
I forgot about that. Let me just close this pull request and open another with that change

**Comment by kumarmanish03** [comment]
Hey @Racing5372 You may also check out this repo https://github.com/CoffeeWithDevs/CodeWithUs

**Pull request closed without merging**
