### PR TITLE
Website-Improvements

### PR DESCRIPTION
**Pull request by georgioupanayiotis**
- update read.me
- fix nav links

### CODE REVIEW

**Comment by geeks5551** [comment]
@georgioupanayiotis HEY can you  provide with the live link or screenshots so that I can review better

**Comment by geeks5551** [comment]
@georgioupanayiotis can you provide the live link/screenshots to help me better reviewing your pr

**Comment by geeks5551** [comment]
@georgioupanayiotis also resolve your merge conflicts

**Comment by georgioupanayiotis** [comment]
@geeks5551  done ✅

**Comment by geeks5551** [comment]
@georgioupanayiotis pls resolve the merge conflicts

**Comment by georgioupanayiotis** [comment]
@geeks5551  done ✅  do not forget the labels 😉
Screenshot 2020-10-23 at 11 06 30

**Pull request merged**
