### PR TITLE
enhanced contact us page and fixed the navigation links

### PR DESCRIPTION
**Pull request by namrata18s**

### CODE REVIEW

**Comment by geeks5551** [comment]
hey @namrata18s pls resolve the merge conflicts

**Comment by namrata18s** [comment]
@geeks5551  resolved the conflicts

**Comment by geeks5551** [comment]
Closed #10 by #15

**Comment by kumarmanish03** [comment]
Hey @namrata18s  You may also check out this repo https://github.com/CoffeeWithDevs/CodeWithUs

**Pull request merged**
