### PR TITLE
styled back to top button issue #2

### PR DESCRIPTION
**Pull request by snehaa1989**
changes:
added css and javascript for smooth scrolling to top
please review my pr, thank you
Here is the ss, please add hacktoberfest accepted
scrolltotop

### CODE REVIEW

**Comment by snehaa1989** [comment]
please open "index.html" in browser for changes

**Comment by geeks5551** [comment]
@snehaa1989 hey can you provide me with the live link/screenshots for helping me to review your  pr better

**Comment by geeks5551** [comment]
hey @snehaa1989 pls resolve the merge conflicts

**Comment by kumarmanish03** [comment]
@snehaa1989 you may also contribute to this repo https://github.com/CoffeeWithDevs/CodeWithUs
Do have a look

**Comment by snehaa1989** [comment]
@geeks5551 I have resolved merge conflicts, please review my pr

**Comment by geeks5551** [comment]
hey @snehaa1989, can you provide a suitable icon for the button , otherwise all is fine

**Comment by geeks5551** [comment]
hey @snehaa1989 any updates?

**Comment by geeks5551** [comment]
@snehaa1989 pls resolve the merge conflicts

**Comment by snehaa1989** [comment]
i added an icon check pls

**Pull request merged**
