### PR TITLE
Should close issue #12 now

### PR DESCRIPTION
**Pull request by groomea**
Added favicon that looks like this that closes issue #12 
image

### CODE REVIEW

**Comment by groomea** [comment]
Also would you be able to add the label "hacktoberfest-accepted" to the issue please? Just so it counts towards my PRs for Hacktoberfest

**Comment by geeks5551** [comment]
hey @Racing5372 i have already added the label so don't worry

**Comment by groomea** [comment]
On the website it says that this is an ineligible repository.
image
According to the Hacktoberfest website you need to either add 'hacktoberfest' to the topics in the repository or add the label ‘hacktoberfest-accepted’ to this issue.
https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by groomea** [comment]
Hey @geeks5551 it still says that it's ineligible. Could you add the label ‘hacktoberfest-accepted’ here please?

**Comment by geeks5551** [comment]
see @Racing5372 I have added the required label.

**Comment by groomea** [comment]
Great thank you!

**Pull request merged**
